#아이리스 품종 분류
- github csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [5]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X) # 다중분류 softmax 
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [13]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5825 - accuracy: 0.8467
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5801 - accuracy: 0.8467
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5780 - accuracy: 0.8267
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5741 - accuracy: 0.8667
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5722 - accuracy: 0.8467
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5682 - accuracy: 0.8467
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5661 - accuracy: 0.8600
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5634 - accuracy: 0.8667
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5610 - accuracy: 0.8467
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5606 - accuracy: 0.8933
Epoch 11/100
5/5 [===========

In [14]:
# 모델을 이용합니다.
model.predict(독립[0:5])

array([[0.8998346 , 0.09426701, 0.00589842],
       [0.8386882 , 0.14981857, 0.01149325],
       [0.8772634 , 0.11410028, 0.00863628],
       [0.8450057 , 0.14110385, 0.01389046],
       [0.91005355, 0.0844462 , 0.00550027]], dtype=float32)

In [15]:
print(종속[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [16]:
model.predict(독립[-5:])

array([[0.01351522, 0.41835165, 0.5681332 ],
       [0.01357302, 0.4028298 , 0.5835972 ],
       [0.01792678, 0.40094995, 0.58112323],
       [0.01481364, 0.32434383, 0.66084254],
       [0.02190399, 0.34872475, 0.6293713 ]], dtype=float32)

In [17]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [18]:
# 학습한 가중치
model.get_weights()

[array([[ 0.6119571 ,  0.71606857,  0.13832702],
        [ 0.16492638, -0.9440497 , -1.120514  ],
        [-0.65112436,  0.09585494,  1.0328133 ],
        [-0.73704344,  0.2767653 ,  0.44495228]], dtype=float32),
 array([ 0.30902082,  0.15485576, -0.39786202], dtype=float32)]